# Generated by Django 5.1.6 on 2025-03-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtupeAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('excluded', models.JSONField(default=list)),
            ],
        ),
    ]
